name: Dependabot Yarn Lock Update

on:
  pull_request:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  update-pnpm-lock:
    # Dependabotのプルリクエストのみに実行
    # if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    # main.ymlからrun --rm appできる状態まで持ってくる
    # Yarnロックファイルを更新
    - name: Update pnpm Lock
      run: |
        pnpm install
    
    # 更新された差分をコミット
    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add pnpm-lock.yaml
        git commit -m "chore: update pnpm-lock.yaml after dependabot package update" || echo "No changes to commit"
    
    # 変更をプッシュ
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}